### ISSUE TITLE
Check Resolution,

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/youlazydawg#11]
This looks like the really old iPhone 3 resolution setup, Do we want to have this?

**Comment by danielkagemann** [comment]
???

**Comment by Practical-DQ** [comment]
There are different resolution setups, currently lazy dawg looks like it is made for the iPhone 3, the iPhone 4&5 were slightly longer and the iPhone 6 &  7 are even bigger still,  to forgetting the stupid bloody iPhone + versions. Doe we really want to make the app look like it was created for iPhone 3?

**Comment by Practical-DQ** [comment]
Started using this in my iphen, not an issue
