### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by danielkagemann** [Elemetric/youlazydawg#15]
Timeline should show the score only for today

**Comment by danielkagemann** [comment]
All jobs in timeline grouped by day with scores

**Comment by Practical-DQ** [comment]
I think timeline should be day, week, month
Anything longer might have historic value... but also starts taking the whole thing to seriously. so i would tend to avoid it

**Comment by danielkagemann** [comment]
![image](https://cloud.githubusercontent.com/assets/10135014/20077685/a9c2bee6-a53d-11e6-8ff8-2ca6ab35932b.png)
Done
