### ISSUE TITLE
Drop User id and Password from setup 

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/youlazydawg#20]
Instead use apple id, only email from partner is needed for invitation

**Comment by danielkagemann** [comment]
getting the apple id or android email is not the easiest part.
but what about the following idea having the benefit that we do not store personal data

* first time for the app you have to set your name
* the backend stores the user and generates a token for rest services and an invite code
* the invite code can be used for friends to get connected

no need for complicated logins
no need for account creation and stuff

**Comment by Practical-DQ** [comment]
Sounds good, Where is the backend, how do we make sure that the backend is secure?

**Comment by danielkagemann** [comment]
backend is on elemetric.de
security via tokens

**Comment by Practical-DQ** [comment]
good, do we need to hash the email invatation lists?

**Comment by danielkagemann** [comment]
the invitation list does not contain emails.
do not and will not do.

i only store ids.

the only thing is to give away the invitation code. but this should not be a thing.
we just have to display it somewhere so that the user can giveaway

**Comment by danielkagemann** [comment]
no workaround at the minute.
