### ISSUE TITLE
Done Scores should show the colours who did them,

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/youlazydawg#42]
Blue for me, red for the commies and both for both

**Comment by danielkagemann** [comment]
![image](https://cloud.githubusercontent.com/assets/10135014/20151132/50bbd260-a6b9-11e6-9341-077db6cfdd4c.png)
would be better with avatar images but works for first release

**Comment by Practical-DQ** [comment]
close, but definatly no cigar, I meant colouring the nochmals button, not the text. in my opinion -
Shading the text doesn't allow me to identify who did easily enough.

**Comment by danielkagemann** [comment]
yes you are right. it is not intuitive.
maybe coloring the button on one hand and put the name in brackets behind the job would be enough to transfer the idea behind to the user

**Comment by Practical-DQ** [comment]
I like the idea. and think it would work well

**Comment by danielkagemann** [comment]
![image](https://cloud.githubusercontent.com/assets/10135014/20169557/7cbabc36-a728-11e6-87ca-7d300fde7413.png)

Done.
