### ISSUE TITLE
retroactively adding items

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/youlazydawg#49]
Suggestion from susanne, allow people to add items retroactively, things like i did ironing yesterday.

Suggestion from me: dont.

but seriously, if we do do this reduce the points they get for it to one and only for the day before. We want people to use the app fairly near real time, not batch at the end of the week. The competition only works when both are 'fighting' today', fighting yesterday seems pointless to me

**Comment by danielkagemann** [comment]
yesterday is gone. i mean it is the same for facebook or twitter. 
we are not a fitness app where you can put your activity from yesterday in
