### ISSUE TITLE
turn ist header into footer, to achieve sticky header with scores

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/youlazydawg#71]

**Comment by danielkagemann** [comment]
Can you make a quick wireframe for that?

**Comment by danielkagemann** [comment]
done

**Comment by danielkagemann** [comment]
![image](https://cloud.githubusercontent.com/assets/10135014/20260528/57512c34-aa5a-11e6-8366-fdbfc662a219.png)

**Comment by danielkagemann** [comment]
done and happy with the result
